# Generated by Django 5.0.7 on 2024-08-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Distributor', 'Distributor'), ('Manufacturer', 'Manufacturer')], max_length=50)),
            ],
        ),
    ]
