# Generated by Django 5.0.7 on 2024-08-02 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('Worker', 'Worker'), ('Manager', 'Manager'), ('Supervisor', 'Supervisor')], max_length=50)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapi.company')),
            ],
        ),
    ]
